// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjzFog1xNfdFg9zpLlnqZ9MoN2JvMSiUk',
    appId: '1:383953123551:web:e02d6ed6a7e75f7ae5516a',
    messagingSenderId: '383953123551',
    projectId: 'orderprocessapp-7eca0',
    authDomain: 'orderprocessapp-7eca0.firebaseapp.com',
    storageBucket: 'orderprocessapp-7eca0.appspot.com',
    measurementId: 'G-2E9DLX36DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpyS5pOXQYwLueQsQWbKwYykxnfxRv20',
    appId: '1:383953123551:android:4c3e6c31938ee4cbe5516a',
    messagingSenderId: '383953123551',
    projectId: 'orderprocessapp-7eca0',
    storageBucket: 'orderprocessapp-7eca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDXhnpR4x0jP-Z0H8ZXoIgF1N_GSwArag',
    appId: '1:383953123551:ios:c08740dcaedf8658e5516a',
    messagingSenderId: '383953123551',
    projectId: 'orderprocessapp-7eca0',
    storageBucket: 'orderprocessapp-7eca0.appspot.com',
    iosBundleId: 'com.example.orderProcessApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDXhnpR4x0jP-Z0H8ZXoIgF1N_GSwArag',
    appId: '1:383953123551:ios:986e891aa443ed0de5516a',
    messagingSenderId: '383953123551',
    projectId: 'orderprocessapp-7eca0',
    storageBucket: 'orderprocessapp-7eca0.appspot.com',
    iosBundleId: 'com.example.orderProcessApp1.RunnerTests',
  );
}
